name = "Our Modpack"
author = "Golan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d4b65e695e3060ef11c9fc839b3eb2a76a96812e21ea366fa240387c965b2fb"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
