name = "Our Modpack"
author = "Golan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddf6aab6f6ee9b831dbcd5636e00bdb85bd0e2d769a3540c718d1c016973b0e6"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
